import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

import Link from 'next/link';
import { getAllFilesMetadata } from '../lib/mdx';

import Layout from "../components/Layout";

export default function Home({ posts }) {
  return (
    <Layout>
      <div className={styles.container}>
            
        <Head>
          <title>Blog: Camilo Ardila</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>

          <h1 className={styles.title}>
          Blog de Camilo Ardila
          </h1>
        
          <p className={styles.grid} align="justify">
            Hola, soy Camilo Ardila. Me gradué como economista, y soy un apasionado por las matemáticas y la programacion.
            <br /> En este blog encontrarás diversos tutoriales, en diferentes lenguajes, sobre ciencia de datos, modelos e inteligencia artificial.
            Así mismo, diferentes tutoriales están dedicamos a narrar mi camino por el mundo de la programación; mis fallos y aciertos, y lo que me hubiera gustado saber antes de comenzar.
            <br /> Por úttimo, y no me nos importante, está mi curriculum, en donde te digo acerca de mi background.

          </p>
          {/* Esta es la manera en que estamos mapeando */}
          <div className={styles.grid}>
            {posts.map((post) => (
              <Link 
                key={post.slug} 
                href={`${post.slug}`} 
                className={styles.card}
              >
                <a className={styles.card}>
                  <h2>{post.title} &rarr;</h2>
                  <p>{post.date}</p>
                </a>
              </Link>
            ))}

          </div>
        </main>

        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{' '}
            <span className={styles.logo}>
              <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
            </span>
          </a>
        </footer>
      </div>
    </Layout>
  )
}

export async function getStaticProps() {
  const posts = await getAllFilesMetadata();
  // console.log(posts); 

  return {
    props: { posts },
  };
}